---
#common properties for all config and will be replaced by active profile.

spring:
  #  main:
  #    allow-circular-references: true
  application:
    name: dual-sync
  profiles:
    active: dev

---
#'dev' profile only

spring:
  config:
    activate:
      on-profile: dev
    logsPath: C:\\logs\\

  kafka:
    max.retries: 3
    max.retry.delay: 200
    consumer-thread-pool-config:
      threadCap: 5
      queuedTaskCap: 20
      threadPrefix: CasprConsumer
      ttlSeconds: 60

server:
  port: 8080


log:
  path: 'C:\\logs\\'


#management:
#  endpoint:
#    beans:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: beans